[package]
name = "bletchley_lib"
version = "0.1.0"
authors = ["Paweł Świątkowski <pawel.swiatkowski@boostcom.no>"]

[dependencies]
openssl = "0.9.11"
rand = "0.3.0"
rust-crypto = "0.2.36"
rustc-serialize = "0.3"
serde_json = "0.9"
